" **********************************************************
" vim-plug Plugin manager
" Make sure you use single quotes

call plug#begin()

" Configurable status line
Plug 'itchyny/lightline.vim'

call plug#end()
" **********************************************************

nnoremap <Plug>MoveLineUp :m -2<CR>
nnoremap <C-Up> <Plug>MoveLineUp
nnoremap <C-K> <Plug>MoveLineUp

xnoremap <Plug>MoveBlockUpOne :m -2<CR>gv=gv
xnoremap <C-Up> <Plug>MoveBlockUpOne
xnoremap <C-K> <Plug>MoveBlockUpOne

nnoremap <Plug>MoveLineDown :m +1<CR>
nnoremap <C-Down> <Plug>MoveLineDown
nnoremap <C-J> <Plug>MoveLineDown

xnoremap <Plug>MoveBlockDownOne :m '>+1<CR>gv=gv
xnoremap <C-Down> <Plug>MoveBlockDownOne
xnoremap <C-J> <Plug>MoveBlockDownOne

set number relativenumber " Hybrid numbering
syntax enable " Enable syntax smart syntax highlighting

" Tab size and indents
set shiftwidth=4
set tabstop=4
set autoindent
set smartindent
set expandtab
set softtabstop=4

" Continue comment marker across lines
set formatoptions+=r

" Turn off line wrapping by default
set nowrap

" Turn off search highlighting
set hls!

" Lightline status bar configuration 
set laststatus=2
set noshowmode " Remove the '--INSERT--' at bottom of screen


" Add git status to lightline status bar
let g:lightline = {
      \ 'colorscheme': 'wombat',
      \ 'active': {
      \   'left': [ [ 'mode', 'paste' ],
      \             [ 'gitbranch', 'readonly', 'filename', 'modified' ] ]
      \ },
      \ 'component_function': {
      \   'gitbranch': 'fugitive#head'
      \ },
      \ }

" Highlight when git commit messages get too long
au FileType gitcommit setlocal tw=72
au FileType gitcommit setlocal cc=+1
