" **********************************************************
" vim-plug Plugin manager
" Make sure you use single quotes

call plug#begin()

" Configurable status line
Plug 'itchyny/lightline.vim'

call plug#end()
" **********************************************************

set number relativenumber " Hybrid numbering
syntax enable " Enable syntax smart syntax highlighting

" Tab size and indents
set shiftwidth=4
set tabstop=4
set autoindent
set smartindent
set expandtab
set softtabstop=4

" Continue comment marker across lines
set formatoptions+=r

" Turn off line wrapping by default
set nowrap

" Turn off search highlighting
set hls!

" Lightline status bar configuration 
set laststatus=2
set noshowmode " Remove the '--INSERT--' at bottom of screen


" Add git status to lightline status bar
let g:lightline = {
      \ 'colorscheme': 'wombat',
      \ 'active': {
      \   'left': [ [ 'mode', 'paste' ],
      \             [ 'gitbranch', 'readonly', 'filename', 'modified' ] ]
      \ },
      \ 'component_function': {
      \   'gitbranch': 'fugitive#head'
      \ },
      \ }

" Syntastic settings
set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*

let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0

" Highlight when git commit messages get too long
au FileType gitcommit setlocal tw=72
au FileType gitcommit setlocal cc=+1
