
" Execute pathogen runtime path manager
execute pathogen#infect()

" **********************************************************
" vim-plug Plugin manager

" Make sure you use single quotes

" Specify a directory for plugins
call plug#begin('~/.local/share/nvim/plugged')

" Shorthand notation; fetches https://github.com/junegunn/vim-easy-align
Plug 'junegunn/vim-easy-align'

" Any valid git URL is allowed
Plug 'https://github.com/junegunn/vim-github-dashboard.git'

" Multiple Plug commands can be written in a single line using | separators
Plug 'SirVer/ultisnips' | Plug 'honza/vim-snippets'

" On-demand loading
Plug 'scrooloose/nerdtree', { 'on':  'NERDTreeToggle' }
Plug 'tpope/vim-fireplace', { 'for': 'clojure' }

" Using a non-master branch
Plug 'rdnetto/YCM-Generator', { 'branch': 'stable' }

" Using a tagged release; wildcard allowed (requires git 1.9.2 or above)
Plug 'fatih/vim-go', { 'tag': '*' }

" Plugin options
Plug 'nsf/gocode', { 'tag': 'v.20150303', 'rtp': 'vim' }

" Plugin outside ~/.vim/plugged with post-update hook
Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --all' }

" Unmanaged plugin (manually installed and updated)
Plug '~/my-prototype-plugin'

" Configurable status line
Plug 'itchyny/lightline.vim'

" Initialize plugin system
call plug#end()

" **********************************************************

set number relativenumber " Hybrid numbering
syntax enable " Enable syntax smart syntax highlighting

" Tab size and indents
set shiftwidth=4
set tabstop=4
set autoindent
set smartindent
set expandtab
set softtabstop=4

" Continue comment marker across lines
set formatoptions+=r

" Turn off line wrapping by default
set nowrap

" Turn off search highlighting
set hls!

" Lightline status bar configuration 
set laststatus=2
set noshowmode " Remove the '--INSERT--' at bottom of screen


" Add git status to lightline status bar
let g:lightline = {
      \ 'colorscheme': 'wombat',
      \ 'active': {
      \   'left': [ [ 'mode', 'paste' ],
      \             [ 'gitbranch', 'readonly', 'filename', 'modified' ] ]
      \ },
      \ 'component_function': {
      \   'gitbranch': 'fugitive#head'
      \ },
      \ }

" Syntastic settings
set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*

let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0

" Highlight when git commit messages get too long
au FileType gitcommit setlocal tw=72
au FileType gitcommit setlocal cc=+1
