#!/bin/bash

# Customises the bash prompt

# Source this file in your .bashrc

function _is_in_git_tree() {
    [[ "$(2>/dev/null git rev-parse --is-inside-work-tree)" = "true" ]]
}

function _git_has_modified_tracked_files() {
    ! git diff-files --quiet
}

function _git_has_untracked_files() {
    [[ $(git ls-files --others --exclude-standard) ]]
}

function _git_has_unmerged_files() {
    [[ $(git ls-files --unmerged) ]]
}

function _git_get_tracked_branch() {
    2>/dev/null git rev-parse --abbrev-ref --symbolic-full-name "@{u}"
}

function _update_ps1() {
    local retcode=$?

    if [[ -z "$BASH_PROMPT_DISABLE_COLOR" ]]; then
        local NOCOL="\[\033[00m\]"
        local BGREEN="\[\033[01;32m\]"
        local BBLUE="\[\033[01;34m\]"
        local RED="\[\033[0;31m\]"
        local YELLOW="\[\033[0;33m\]"
    fi

    PS1="$BASH_PROMPT_PREFIX"

    # Set terminal title = "[username]@[hostname]:[path]"
    PS1+="\[\e]0;\u@\h:\w\a\]"

    # Number of jobs
    local jobs
    jobs="$(jobs | wc -l)"
    if [[ "${jobs}" -ne 0 ]]; then
        PS1+="[${jobs}] "
    fi

    # virtualenv
    if [[ -n "$VIRTUAL_ENV" ]]; then
        PS1+="($(basename -- "$VIRTUAL_ENV")) "
    fi

    # conda env
    if [[ -n "$CONDA_DEFAULT_ENV" ]]; then
        PS1+="(🐍 $CONDA_DEFAULT_ENV) "
    fi

    # chroot info
    PS1+="${debian_chroot:+($debian_chroot)}"

    # "[username]@[hostname]:[path]"
    PS1+="${BASH_PROMPT_USER_HOST_PREFIX}${BGREEN}\u@\h${NOCOL}:${BBLUE}\w${NOCOL}"

    # Show git info
    if [[ -n "${BASH_PROMPT_SHOW_GIT}" ]] && _is_in_git_tree; then
        local branch
        local current_color;

        branch=$(git branch --show-current)

        if _git_has_unmerged_files; then
            PS1+="${YELLOW}"
            current_color="${YELLOW}"
        else
            current_color="${NOCOL}"
        fi

        if [[ -z "$branch" ]]; then
            branch=detached@$(git rev-parse --short HEAD)
        fi
        PS1+=" ($branch"

        if _git_has_modified_tracked_files; then
            PS1+="*"
        fi
        if _git_has_untracked_files; then
            PS1+="?"
        fi

        # Show commits ahead/behind of remote
        local tracked_branch
        if [[ "$branch" ]] && tracked_branch=$(_git_get_tracked_branch); then
            local ahead
            local behind
            ahead=$(2>/dev/null git rev-list --count "@{upstream}"..)
            behind=$(2>/dev/null git rev-list --count .."@{upstream}")
            if [[ "${ahead:-0}" -ne 0 && "${behind:-0}" -ne 0 ]]; then
                PS1+=" ${YELLOW}+${ahead}/-${behind}:${tracked_branch}${current_color}"
            elif [[ "${ahead:-0}" -ne 0 ]]; then
                PS1+=" +${ahead}:${tracked_branch}"
            elif [[ "${behind:-0}" -ne 0 ]]; then
                PS1+=" -${behind}:${tracked_branch}"
            fi
        else
            PS1+=" [not tracked]"
        fi

        # Show number of stashes
        local stash
        stash=$(git stash list | wc -l)
        if [[ "${stash}" -ne 0 ]]; then
            PS1+=" stash@${stash}"
        fi

        PS1+=")${NOCOL} "
    fi

    # Show previous returncode if non-zero
    if [[ "$retcode" -ne 0 ]]; then
        PS1+="${RED}[$retcode]\$${NOCOL}"
    else
        PS1+="$"
    fi

    PS1+=" "
}

if [[ $TERM != linux && ! $PROMPT_COMMAND =~ _update_ps1 ]]; then
    PROMPT_COMMAND="_update_ps1; $PROMPT_COMMAND"
fi
