#!/bin/bash

# Customises the bash prompt

# Source this file in your .bashrc

function _update_ps1() {
    local retcode=$?

    local NOCOL="\[\033[00m\]"
    local BGREEN="\[\033[01;32m\]"
    local BBLUE="\[\033[01;34m\]"
    local RED="\[\033[0;31m\]"
    local YELLOW="\[\033[0;33m\]"

    # Set terminal title = "[username]@[hostname]:[path]"
    PS1="\[\e]0;\u@\h:\w\a\]"

    # Number of jobs
    local jobs
    jobs="$(jobs | wc -l)"
    if [[ "${jobs}" -ne 0 ]]; then
        PS1+="[${jobs}] "
    fi

    # virtualenv
    if [[ -n "$VIRTUAL_ENV" ]]; then
        PS1+="($(basename -- "$VIRTUAL_ENV")) "
    fi

    # chroot info
    PS1+="${debian_chroot:+($debian_chroot)}"

    # "[username]@[hostname]:[path]"
    PS1+="${BGREEN}\u@\h${NOCOL}:${BBLUE}\w${NOCOL}"

    # Show git info
    local branch
    if branch=$(2>/dev/null git branch --show-current); then
        # Set colour to yellow if there are conflicts
        if [[ -n "$(git diff --name-only --diff-filter=U --relative)" ]]; then
            PS1+="${YELLOW}"
        fi

        if [[ -z "$branch" ]]; then
            branch=detached@$(git rev-parse --short HEAD)
        fi

        PS1+=" ($branch"

        # Add asterisk if there are uncommitted changes
        if [[ -n "$(git status -s)" ]]; then
            PS1+="*"
        fi

        # Show commits ahead/behind of remote
        local ahead
        local behind
        ahead=$(2>/dev/null git rev-list --count "@{upstream}"..)
        behind=$(2>/dev/null git rev-list --count .."@{upstream}")
        if [[ "${ahead:-0}" -ne 0 && "${behind:-0}" -ne 0 ]]; then
            PS1+=" +${ahead}/-${behind}"
        elif [[ "${ahead:-0}" -ne 0 ]]; then
            PS1+=" +${ahead}"
        elif [[ "${behind:-0}" -ne 0 ]]; then
            PS1+=" -${behind}"
        fi

        # Show number of stashes
        local stash
        stash=$(git stash list | wc -l)
        if [[ "${stash}" -ne 0 ]]; then
            PS1+=" stash@${stash}"
        fi

        PS1+=")${NOCOL} "
    fi

    # Show previous returncode if non-zero
    if [[ "$retcode" -ne 0 ]]; then
        PS1+="${RED}[$retcode]\$${NOCOL}"
    else
        PS1+="$"
    fi

    PS1+=" "
}

if [[ $TERM != linux && ! $PROMPT_COMMAND =~ _update_ps1 ]]; then
    PROMPT_COMMAND="_update_ps1; $PROMPT_COMMAND"
fi
